steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gift_bouqet_be', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gift_bouqet_be']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'gift_bouqet_be',
        '--image', 'gcr.io/$PROJECT_ID/gift_bouqet_be',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--port', '8080',
        '--timeout', '900s',
        '--memory', '512Mi',
        '--cpu', '1',
        '--min-instances', '0',
        '--max-instances', '10'
      ]

images:
  - 'gcr.io/$PROJECT_ID/gift_bouqet_be'

options:
  logging: CLOUD_LOGGING_ONLY
